# This is an example Mocha config containing every Mocha option plus others
allow-uncaught: false
async-only: false
bail: true
check-leaks: true
color: true
delay: false
diff: true
exit: true # could be expressed as "no-exit: true"
extension:
  - 'js'
# fgrep and grep are mutually exclusive
# fgrep: something
forbid-only: false
forbid-pending: false
full-trace: true
# fgrep and grep are mutually exclusive
# grep: something
growl: false
inline-diffs: false
# needs to be used with grep or fgrep
# invert: false
recursive: false
retries: 1
require:
  - ts-node/register
  - source-map-support/register
slow: 1000
sort: false
spec: 'test/**/*.test.ts'
timeout: 5000 # same as "no-timeout: true" or "timeout: 0"
trace-warnings: true # node flags ok
ui: 'bdd'
v8-stack-trace-limit: 100 # V8 flags are prepended with "v8-"
watch: false
watch-files:
  - 'src/**/*.ts'
  - 'test/**/*.ts'